### ISSUE TITLE
Ubuntu 22.04.2 LTS?

### ISSUE THREAD

**Issue by GustavBrock** [VeeamHub/veeam-hardened-repository#2]
Will this - or is it planned to - support the current Ubuntu 22.04.2 LTS?

**Comment by tsightler** [comment]
I'm not 100% sure of this, but I don't think DISA has release a STIG for Ubuntu 22.04 yet.  It usually takes a little over a year after release for the DISA STIG to follow, but I haven't seen any announcement of a DISA STIG profile for Ubuntu 22.04.  Overall, I'd guess the steps in this script would mostly work.

In the end, if you need hardened OS, you will almost always need to stay conservative on OS versions because the hardening details almost always lag from the initial release.

**Comment by GustavBrock** [comment]
Thanks. That makes sense..
